variables:
  AZURE_WEBAPP_API_NAME: "nutritrack"
  AZURE_RESOURCE_GROUP: "pol-RG"
  AZURE_TENANT_ID: "df7af033-797d-45df-a398-a177b1e00f28"

stages:
  - build
  - deploy

before_script:
  - cd $CI_PROJECT_DIR

build-api:
  image: mcr.microsoft.com/dotnet/sdk:8.0.101
  stage: build
  script:
    - cd NutritionalRecipeBook/src
    - dotnet publish -c Release -o ./publish
  artifacts:
       paths: 
          - $CI_PROJECT_DIR/NutritionalRecipeBook/src/publish/*
  only:
    - develop

deploy-api:
  image: mcr.microsoft.com/dotnet/sdk:8.0.101
  stage: deploy
  dependencies:
    - build-api
  script:
    - apt-get update 
    - apt-get install zip unzip
    - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
    - cd $CI_PROJECT_DIR/NutritionalRecipeBook/src/publish
    - zip -r ../publish.zip .
    - cd ..
    - az login --tenant $AZURE_TENANT_ID
    - az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_API_NAME --src publish.zip
